from __future__ import annotations
from typing import Protocol
from sylphos.runtime.context import RuntimeContext
from sylphos.runtime.events import ToolExecutionRequested
class ToolExecutor(Protocol):
    name: str
    def execute(self, request: ToolExecutionRequested, context: RuntimeContext) -> dict: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
