from __future__ import annotations
from typing import Protocol
class WakeWordEngine(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
