AUDIO_INPUT_DEVICE_INDEX = 3
AUDIO_INPUT_DEVICE_NAME = '麦克风 (BOYA mini)'

INPUT_RATE = 44100
CHANNELS = 1
BLOCKSIZE = 4410
DTYPE = "float32"

WAKEWORD_MODEL_SOURCE = 'openwakeword_resource'
WAKEWORD_MODEL_NAME = 'hey_jarvis_v0.1.onnx'
WAKEWORD_MODEL_RELATIVE_PATH = None
WAKEWORD_THRESHOLD = 0.5
WAKEWORD_COOLDOWN_SECONDS = 2.0

RECORDINGS_DIR = 'recordings'

# > 0: 固定时长录音
# <= 0: 使用 VAD 自动结束
# VAD（仅在 COMMAND_RECORD_SECONDS <= 0 时生效）
COMMAND_RECORD_SECONDS = 0
